#!/usr/bin/bash
set -euo pipefail

# -------------------------------------------------------------
# CONFIGURATION
# -------------------------------------------------------------
JAR_NAME="EBCoordinator.jar"
SERVICE_NAME="experiencebufferscoordinator.service"
TARGET_DIR="$HOME/ExperienceBuffers"
INSTALL_DIR="${TARGET_DIR}/lib"

# -------------------------------------------------------------
# FUNCTIONS
# -------------------------------------------------------------

# -------------------------------------------------------------
checkRequirements() {
	echo
    echo "Checking system requirements..."

    # Check Java
    if command -v java >/dev/null 2>&1; then
        echo "Java found: $(java -version 2>&1 | head -n 1)"
    else
        echo "Java not found. Installing OpenJDK..."
        sudo apt-get update
        sudo apt-get install -y default-jdk
    fi
}

# -------------------------------------------------------------
installJar() {
	echo
    echo "Installing JAR..."
	
	URL="https://github.com/lmgardere/ExperienceBuffers/releases/latest/download/$JAR_NAME"
	
	echo "Downloading $URL"
    sudo mkdir -p $INSTALL_DIR
    curl -LO "$URL"
    sudo mv $JAR_NAME $INSTALL_DIR/$JAR_NAME

	# File exists but not executable
	if [ ! -x "$INSTALL_DIR/$JAR_NAME" ]; then
	    echo "${JAR_NAME} exists but is not executable. Fixing permissions..."
	    chmod 755 "$INSTALL_DIR/$JAR_NAME"
	fi

    echo "JAR installed to ${INSTALL_DIR}"
}

# -------------------------------------------------------------
createService() {
	echo
    echo "Creating systemd service..."

	sudo ln -sf $INSTALL_DIR /root
    sudo mkdir -p /usr/lib/ExperienceBuffers
	sudo ln -sf $INSTALL_DIR/$JAR_NAME /usr/lib/ExperienceBuffers
	
	# Copy systemd service file
	chmod 644 $TARGET_DIR/$SERVICE_NAME
	sudo ln -sf $TARGET_DIR/$SERVICE_NAME /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable $SERVICE_NAME
    sudo systemctl restart $SERVICE_NAME

    echo "Service ${SERVICE_NAME} installed and started."
}

# -------------------------------------------------------------
main() {
    echo "=== ExperienceBuffers Coordinator Installer ==="
    checkRequirements
    installJar
    createService
    echo "Installation complete."
}

# -------------------------------------------------------------
main